### ISSUE TITLE
깃허브에서 뱃지가 Unknown으로 표시됨

### ISSUE THREAD

**Issue by testafor** [2ykwang/solvedac-readme-badge#5]
오늘 아침까지 괜찮았던 것 같습니다.
큰 뱃지의 유저 레이팅이 Unknown으로 바뀌었고, 
Compact 버전에서도 U로 바뀌었습니다.
당연히 큰 뱃지에서 다른 유저 정보도 나오지 않습니다.
api 변경이 있나 해서 노션에 넣어봤는데 노션에서는 정상 작동 합니다.
깃허브에서 뭔가 업데이트를 한 듯 한데 확인 부탁드립니다.

**Comment by 2ykwang** [comment]
네 이따가 확인해볼게요. 

Unknown 으로 표시되는경우 API 호출 실패 케이스로 예상되는데, 
GitHub에서만 Unknown으로 표시되고 노션에서는 잘 표시된다는 말씀이신거죠?

GitHub 이미지가 API 호출 실패했을 때 이미지 결과값을 캐싱하고 있을수도 있어서 
쿼리 파라미터 값을 변경하여 다시 시도해보실 수 있나요? @testafor

**Comment by testafor** [comment]
> 네 이따가 확인해볼게요.
> 
> Unknown 으로 표시되는경우 API 호출 실패 케이스로 예상되는데, GitHub에서만 Unknown으로 표시되고 노션에서는 잘 표시된다는 말씀이신거죠?
> 
> GitHub 이미지가 API 호출 실패했을 때 이미지 결과값을 캐싱하고 있을수도 있어서 쿼리 파라미터 값을 변경하여 다시 시도해보실 수 있나요? @testafor

말씀 듣고 파라미터 수정하러 들어가 봤는데 지금은 또 정상으로 돌아와 있네요. 
몇십 분 확인하고 이슈 올렸던 건데 뻘쭘하네요. 감사합니다.

**Comment by testafor** [comment]
> 네 이따가 확인해볼게요.
> 
> Unknown 으로 표시되는경우 API 호출 실패 케이스로 예상되는데, GitHub에서만 Unknown으로 표시되고 노션에서는 잘 표시된다는 말씀이신거죠?
> 
> GitHub 이미지가 API 호출 실패했을 때 이미지 결과값을 캐싱하고 있을수도 있어서 쿼리 파라미터 값을 변경하여 다시 시도해보실 수 있나요? @testafor

말씀 듣고 파라미터 수정하러 들어가 봤는데 지금은 또 정상으로 돌아와 있네요.
몇십 분 확인하고 이슈 올렸던 건데 뻘쭘하네요. 감사합니다.
